"""empty message

Revision ID: 3d4ade08c770
Revises: 6ebe9aca7cd2
Create Date: 2018-02-16 15:11:47.729528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4ade08c770'
down_revision = '6ebe9aca7cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='foreignkey')
    # ### end Alembic commands ###
